# -*- coding: utf-8 -*-
"""Choncha_Hangman_project_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkcB9HqQXhkXc-mlBsMFDf7ZIeW38Ueo
"""

import random

print("Welcome to Hangman Challenge")

#Select a random secret word
word_list = ["survey","function","remain","transmission","strap","digital","enhance","crackpot","bedroom","resolution","parade","dimension","locate","contract","please","ribbon","hemisphere","offset","cotton","retired","flower","rifle","hallway","adoption","council","difference","percent","observation","friendly","momentum","patience","extinct","concert","brush","electron","bracket","deviation","output","betray","convict","admire","manufacture","cream","spectrum","printer","hardship","mislead","shout","magazine","meaning","possibility","basin","physical","honor","sensitive","helicopter","cylinder","nursery","motif","rocket","ticket","bulletin","offend","nonremittal","sacrifice","height","artist","celebration","motorist","remind","crystal","teacher","drink","experience","letter","potential","feeling","calculation","smile","lounge","outlet","subway","lighter","accompany","compensation","society","marsh","redeem","alarm","suffering","collapse","dribble","mastermind","agile","limit","business","strange","extort","autonomy","handy"]
secret_word = random.choice(word_list)


correct_word = secret_word.upper()
hidden_word = "_ "*len(correct_word)
correct_guessed_word = ""
wrong_time = 0

print("The secret word is: ", hidden_word)

#Validate the entry
valid_entry = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
guessed_word = ""
guessed_letter = ""

while wrong_time < 6 or correct_guessed_word != correct_word:
    if correct_guessed_word == correct_word:
        print("Congratulation YOU WIN!!!")
        break
    print("---------------------------------------------------------------")
    guessed_letter = input("Guess a letter: ").upper()
#Only for the input which are alphabets and not repeated
    if guessed_letter in valid_entry and guessed_letter not in guessed_word and len(guessed_letter) == 1:
        guessed_word += guessed_letter
#Check the correct alphabet and put on the hidden_word
        if guessed_letter in correct_word:
          for i in range(len(correct_word)):
              if guessed_letter == correct_word[i]:
                  hidden_word = hidden_word[:2*i] + guessed_letter + hidden_word[2*i+1:]
                  correct_guessed_word = hidden_word.replace(" ", "")
          print("You have guessed correctly!")
          print(hidden_word)
#Increase amout of false attempt
        else:
              wrong_time += 1
              print("Wrong guess, you have ", 6 - wrong_time, "more times to try")
              print("The secret word is: ", hidden_word)
#Create a Hangman visual
              if wrong_time == 1:
                print("""
                  ------
                   O   |
                       |
                       |
                       |
                       |
                       |
                ////////////////////
                """)
              elif wrong_time == 2:
                print("""
                  ------
                   O   |
                   |   |
                       |
                       |
                       |
                       |
                ////////////////////
                """)
              elif wrong_time == 3:
                print("""
                ------
                   O   |
                  /|   |
                       |
                       |
                       |
                       |
                ////////////////////
                """)
              elif wrong_time == 4:
                print("""
                ------
                   O   |
                  /|\  |
                       |
                       |
                       |
                       |
                ////////////////////
                """)
              elif wrong_time == 5:
                print("""
                ------
                   O   |
                  /|\  |
                   |   |
                  /    |
                       |
                       |
                ////////////////////
                """)
              elif wrong_time == 6:
                print("""
                ------
                   O   |
                  /|\  |
                   |   |
                  / \  |
                       |
                  YOU ARE DEAD!!!
                ////////////////////
                """)
                print("The correct word is: ", correct_word)
                break

    elif guessed_letter in guessed_word:
        print("You have already guessed that letter")
    else:
        print("Invalid input, only 1 alphapet is expected")